<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\InventoryMovement;
use App\Models\Order;
use App\Models\OrderItem;
use App\Models\Product;
use App\Models\Supplier;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

class DemoDataSeeder extends Seeder
{
    private const CATEGORY_NAMES = [
        'Vegetable Seeds', 'Flower Seeds', 'Live Plants', 'Bulbs & Tubers',
        'Soil & Fertilizer', 'Pots & Planters', 'Tools & Equipment', 'Irrigation & Watering',
    ];

    public function run(): void
    {
        $suppliers = Supplier::factory(10)->create();

        $categories = collect(self::CATEGORY_NAMES)->map(fn ($name) => Category::create([
            'name' => $name,
            'slug' => Str::slug($name),
        ]));

        $products = Product::factory(150)
            ->recycle($suppliers)
            ->recycle($categories)
            ->create();

        $this->seedMovementHistory($products);
        $this->seedOrders($products);
        $this->writeSampleFeed($products);
    }

    private function seedMovementHistory($products): void
    {
        $rows = [];
        $now = now();

        foreach ($products as $product) {
            for ($monthsAgo = 6; $monthsAgo >= 0; $monthsAgo--) {
                $restockDate = $now->copy()->subMonths($monthsAgo)->startOfMonth()->addDays(rand(0, 5));

                $rows[] = $this->movementRow($product->id, 'in', rand(80, 250), $restockDate, 'supplier_feed');

                foreach (range(1, rand(3, 10)) as $_) {
                    $saleDate = $restockDate->copy()->addDays(rand(1, 27));
                    $rows[] = $this->movementRow($product->id, 'out', rand(1, 20), $saleDate, 'sale');
                }
            }
        }

        foreach (array_chunk($rows, 500) as $chunk) {
            InventoryMovement::insert($chunk);
        }
    }

    private function movementRow(int $productId, string $type, int $quantity, Carbon $occurredAt, string $source): array
    {
        return [
            'product_id' => $productId,
            'type' => $type,
            'quantity' => $quantity,
            'occurred_at' => $occurredAt,
            'source' => $source,
            'created_at' => $occurredAt,
            'updated_at' => $occurredAt,
        ];
    }

    private function seedOrders($products): void
    {
        Order::factory(80)->create()->each(function (Order $order) use ($products) {
            foreach ($products->random(rand(1, 4)) as $product) {
                OrderItem::create([
                    'order_id' => $order->id,
                    'product_id' => $product->id,
                    'quantity' => rand(1, 6),
                    'unit_price' => $product->unit_price,
                ]);
            }
        });
    }

    /**
     * Writes storage/app/feeds/sample-supplier-feed.csv against the SKUs
     * that actually exist in this run (they're randomly generated by the
     * factory), plus a handful of deliberately bad rows so `inventory:import`
     * has something real to validate and skip.
     */
    private function writeSampleFeed($products): void
    {
        $path = storage_path('app/feeds/sample-supplier-feed.csv');
        @mkdir(dirname($path), 0755, true);

        $handle = fopen($path, 'w');
        fputcsv($handle, ['sku', 'quantity_received', 'unit_cost', 'received_at']);

        foreach ($products->random(25) as $product) {
            fputcsv($handle, [
                $product->sku,
                rand(20, 150),
                round($product->unit_price * 0.6, 2),
                now()->subDays(rand(0, 2))->toDateString(),
            ]);
        }

        // A vendor-prefixed SKU that NormalizeSku should clean up.
        fputcsv($handle, ['VND:'.$products->first()->sku, 40, 2.10, now()->toDateString()]);

        // Deliberately bad rows to exercise ValidateRow / UpsertProduct skip paths.
        fputcsv($handle, ['', 50, 1.50, now()->toDateString()]);
        fputcsv($handle, ['ZZ-9999', 50, 1.50, now()->toDateString()]);
        fputcsv($handle, [$products->last()->sku, -5, 1.50, now()->toDateString()]);
        fputcsv($handle, [$products->last()->sku, 50, 1.50, 'not-a-date']);

        fclose($handle);
    }
}
